const mongoose = require("mongoose");

const chatSchema = new mongoose.Schema(
  {
    // Links chat to a specific user
    // If auth is enabled, this stores the user's MongoDB _id
    userId: {
      type: mongoose.Schema.Types.Mixed,
      // Accepts both ObjectId (logged in user) and String ("guest")
      default: "guest",
    },

    // The message typed by the student
    userMessage: {
      type: String,
      required: [true, "User message is required"],
      trim: true,
      minlength: [1, "Message cannot be empty"],
      maxlength: [5000, "Message too long"],
    },

    // The response generated by Gemini AI
    aiResponse: {
      type: String,
      required: [true, "AI response is required"],
      trim: true,
    },

    // Which AI model generated the response
    model: {
      type: String,
      default: "gemini-2.5-flash",
      enum: [
        "gemini-2.5-flash-preview-04-17",
        "gemini-2.5-flash",
        "gemini-2.5-pro",
        "gemini-2.5-flash-lite",
        "gemini-1.5-flash",
        "gemini-pro",
      ],
    },

    // Topic/category of the question — optional for future filtering
    topic: {
      type: String,
      default: "general",
      trim: true,
    },

    // Was the response helpful? — optional future feature
    isHelpful: {
      type: Boolean,
      default: null,
    },

    // When this chat message was created
    timestamp: {
      type: Date,
      default: Date.now,
    },
  },
  {
    // Auto adds createdAt and updatedAt
    timestamps: true,
  }
);

// ✅ Index for faster queries when fetching user chat history
chatSchema.index({ userId: 1, timestamp: -1 });

// ✅ Static method — get chat history for a specific user
chatSchema.statics.getUserHistory = async function (userId, limit = 50) {
  return await this.find({ userId })
    .sort({ timestamp: -1 })
    .limit(limit)
    .select("userMessage aiResponse model topic timestamp");
};

// ✅ Static method — get total chat count for a user
chatSchema.statics.getUserChatCount = async function (userId) {
  return await this.countDocuments({ userId });
};

module.exports = mongoose.model("Chat", chatSchema);