// backend/models/Document.js
const mongoose = require("mongoose");

const documentSchema = new mongoose.Schema(
  {
    // Who uploaded this document
    userId: {
      type: mongoose.Schema.Types.Mixed,
      required: [true, "userId is required"],
      default: "guest",
    },

    // Original filename as uploaded by the user
    originalName: {
      type: String,
      required: [true, "Original filename is required"],
      trim: true,
    },

    // The filename we saved on disk (unique, generated by us)
    storedName: {
      type: String,
      required: [true, "Stored filename is required"],
    },

    // Full path on disk — used to read the file later
    filePath: {
      type: String,
      required: [true, "File path is required"],
    },

    // File size in bytes — useful for display and limits
    fileSize: {
      type: Number,
      required: true,
    },

    // MIME type — should be application/pdf for now
    mimeType: {
      type: String,
      required: true,
      default: "application/pdf",
    },

    // The extracted plain text from the PDF
    // This is what we send to Gemini as context
    extractedText: {
      type: String,
      default: "",
    },

    // How many pages the PDF had
    pageCount: {
      type: Number,
      default: 0,
    },

    // Short AI-generated summary of the document (we'll add this later)
    summary: {
      type: String,
      default: "",
    },

    // Processing status — so frontend knows if file is ready
    status: {
      type: String,
      enum: ["uploading", "processing", "ready", "failed"],
      default: "uploading",
    },

    // Optional label the user can give their document
    title: {
      type: String,
      trim: true,
      default: "",
    },
  },
  {
    timestamps: true, // adds createdAt and updatedAt automatically
  }
);

// Index for fast lookup of all documents belonging to a user
documentSchema.index({ userId: 1, createdAt: -1 });

// Static method — get all documents for a specific user
documentSchema.statics.getUserDocuments = async function (userId) {
  return await this.find({ userId })
    .sort({ createdAt: -1 })
    .select("originalName title fileSize pageCount status summary createdAt");
};

module.exports = mongoose.model("Document", documentSchema);